### ISSUE TITLE
Question: Get hebrew date as string

### ISSUE THREAD

**Issue by ds1239** [MosheBerman/KosherCocoa#11]
Hello,
How would I go about getting the hebrew date as a string? The format I would like it in: (month day, year).
I would just have an array of month names, and choose which one based on the "currentHebrewMonth" variable, but the fact that there are several different possible hebrew year lengths makes it a lot more complicated. Thanks!

**Comment by MosheBerman** [comment]
Look at the [NSDateFormatter class](https://developer.apple.com/library/mac/documentation/Cocoa/Reference/Foundation/Classes/NSDateFormatter_Class/index.html#//apple_ref/occ/instm/NSDateFormatter/shortMonthSymbols).
