### ISSUE TITLE
isCholHamoedSuccos() returns true on Chol Hamoed Pesach.

### ISSUE THREAD

**Issue by sharshi** [MosheBerman/KosherCocoa#117]
I'm testing an application by changing the date of my phone to April 25-27 2016 which is Chol Hamoed Pesach, and `KCJewishCalendar...isCholHamoedSuccos()` is returning true.

Wonderful library.

**Comment by sharshi** [comment]
#118 fixes it AFAIK. Tested in Israel, Chu"l on Pesach and Sukkos, no issues for me.

**Comment by MosheBerman** [comment]
Thank you!

**Comment by MosheBerman** [comment]
Merged #118
