### ISSUE TITLE
Swift 4.0

### ISSUE THREAD

**Issue by IsraelDev** [MosheBerman/KosherCocoa#126]
Did anyone test this project with a Swift 4.0 project? #121

**Comment by MosheBerman** [comment]
Not yet, nope. It's Objective-C, so unless interoperability changed significantly, it should still work. If you have time to look at integrating with Swift 4.0 or to research #121, please do by all means.

**Comment by MosheBerman** [comment]
I'm actually going to self-assign this so I can do a nullability audit to make working with this in Swift nicer.

**Comment by sharshi** [comment]
I used this in a Swift 4.0 project with no issues AFAIK.
