### ISSUE TITLE
Bug in day of year calculation

### ISSUE THREAD

**Issue by BehindTheMath** [MosheBerman/KosherCocoa#132]
Since this library is a port of [KosherJava](https://github.com/KosherJava/zmanim), I believe that [this bug](https://github.com/KosherJava/zmanim/issues/110) also applies to this library.

I don't know anything about Objective-C, but I believe [these](https://github.com/MosheBerman/KosherCocoa/blob/27761a714ba05f3c7ebddf38c60559d0b4dce595/KosherCocoa/Library/Core/Solar/KCSunriseAndSunsetCalculator.m#L281-L295) are the relevant lines.

**Comment by MosheBerman** [comment]
Excellent find. `NSCalendar` has some code to calculate this, so I'll have a crack at fixing it shortly. Thanks!

**Comment by BehindTheMath** [comment]
Turns out I was wrong, at least regarding Java (see [here](https://github.com/KosherJava/zmanim/issues/110#issuecomment-332042090)).

I don't know how arithmetic works in Objective-C, so I believe this should still be looked in to.

**Comment by MosheBerman** [comment]
This is still a good argument for writing tests. 😊
