### ISSUE TITLE
Effects of elevation

### ISSUE THREAD

**Issue by greatjack1** [MosheBerman/KosherCocoa#133]
This is not a issue with the kosher cocoa lib, however since the kosher cocoa lib also uses elevation to calculate zmanim, I thought you might have a answer to my question.

I put up a web based zmanim api service at [https://wyrezmanim.herokuapp.com](https://wyrezmanim.herokuapp.com). Source code is at [https://github.com/greatjack1/dotnetcoreZmanim](https://github.com/greatjack1/dotnetcoreZmanim) and I wanted to know if I should make elevation be a required parameter when calculating zmanim or not? Does it make a big enough difference that I should force users to add it?

**Comment by MosheBerman** [comment]
Generally we use sea-level but some folks hold by elevation, so it's included.
