### ISSUE TITLE
After sunset working date changes, how to override

### ISSUE THREAD

**Issue by IsraelDev** [MosheBerman/KosherCocoa#138]
The function `KCJewishCalendar workingDateAdjustedForSunset` always runs even when I pass in a different date. Sometimes I don't want the day after, even if it's after sunset, how do I override?

**Comment by Elyahu41** [comment]
Just edit the method to not use workingDateAdjustedForSunset and to use workingDate instead.

**Comment by MosheBerman** [comment]
Duplicate of #142, addressed in PR #156
