### ISSUE TITLE
NOAA Sunrise Calculator?

### ISSUE THREAD

**Issue by Elyahu41** [MosheBerman/KosherCocoa#145]
Hey! I noticed that this library uses the SunTimesCalculator.java file for sunrise and sunset calculations from the KosherJava library. Why was this Algorithm chosen over the default NOAA Algorithm?

Also, is there any plan to include the NOAA Algorithm? Because on the KosherJava website, he writes that the NOAA Algorithm is more accurate. See here: https://kosherjava.com/2022/01/12/equinox-vs-equilux-zmanim-calculations/

"As noted above, the degree-based calculations were done using the more accurate Jean Meeus / NOAA algorithms. Seforim printed in the past did not have access to the newer algorithms and typically used the [USNO algorithm](https://github.com/KosherJava/zmanim/blob/master/src/main/java/com/kosherjava/zmanim/util/SunTimesCalculator.java), but as seen below, there is only a trivial difference between the algorithms."

**Comment by MosheBerman** [comment]
Thank you for your contribution!
