### ISSUE TITLE
KCParashatHashavuaCalculator

### ISSUE THREAD

**Issue by dovberPersiko** [MosheBerman/KosherCocoa#6]
Hi.

I have so say KosherCocoa is amazing.
Just one bug I found in KCParashatHashavuaCalculator.

When i trying to search parsha in israel between 22-29 in Elul this year , my application is about to crush.
I don't know why ,can you help me with that ?

**Comment by MosheBerman** [comment]
Should be good now.

**Comment by dovberPersiko** [comment]
Thanks
