### ISSUE TITLE
Installing via Cocoapods does not work

### ISSUE THREAD

**Issue by nilsou** [MosheBerman/KosherCocoa#7]
In your Cocoapods spec there is a typo that prevents it from finding any file:

"KosherCocoa/Library/**.{h,m}" should probably be "KosherCocoa/Library/*/*.{h,m}"

Thank you!

**Comment by MosheBerman** [comment]
There's been some talk about Swift and CocoaPods recently. Anyone have any updates?

**Comment by arytbk** [comment]
Here is the latest update as far as I know, it contains great advice too:
http://blog.cocoapods.org/Pod-Authors-Guide-to-CocoaPods-Frameworks

**Comment by natanrolnik** [comment]
@MosheBerman the only file included when installed via CocoaPods is KosherCocoa.h.
![captura de tela 2015-03-05 as 02 58 51](https://cloud.githubusercontent.com/assets/1164565/6497076/97930188-c2e3-11e4-9178-974124f548c6.png)

**Comment by zleight1** [comment]
Can confirm this is still an issue

**Comment by MosheBerman** [comment]
Can anyone look at the pod file and make necessary changes?

**Comment by MosheBerman** [comment]
I'm in the process of converting to a Framework, trying to figure out the new CocoaPods stuff.

**Comment by MosheBerman** [comment]
Added Cocoapods for 3.0.2. Please confirm that the new pod (completely rewritten) works as expected.
